'use strict';
const API = {
  geocode: 'https://geocoding-api.open-meteo.com/v1/search',
  weather: 'https://api.open-meteo.com/v1/forecast',
  reverse: 'https://nominatim.openstreetmap.org/reverse'
};
const WMO = {
  0:{icon:'☀️',label:'Clear Sky',bg:'clear'},1:{icon:'🌤️',label:'Mainly Clear',bg:'clear'},
  2:{icon:'⛅',label:'Partly Cloudy',bg:'cloudy'},3:{icon:'☁️',label:'Overcast',bg:'cloudy'},
  45:{icon:'🌫️',label:'Foggy',bg:'fog'},48:{icon:'🌫️',label:'Rime Fog',bg:'fog'},
  51:{icon:'🌦️',label:'Light Drizzle',bg:'rain'},53:{icon:'🌦️',label:'Drizzle',bg:'rain'},
  55:{icon:'🌦️',label:'Heavy Drizzle',bg:'rain'},61:{icon:'🌧️',label:'Light Rain',bg:'rain'},
  63:{icon:'🌧️',label:'Rain',bg:'rain'},65:{icon:'🌧️',label:'Heavy Rain',bg:'rain'},
  71:{icon:'🌨️',label:'Light Snow',bg:'snow'},73:{icon:'❄️',label:'Snow',bg:'snow'},
  75:{icon:'❄️',label:'Heavy Snow',bg:'snow'},77:{icon:'🌨️',label:'Snow Grains',bg:'snow'},
  80:{icon:'🌦️',label:'Light Showers',bg:'rain'},81:{icon:'🌧️',label:'Showers',bg:'rain'},
  82:{icon:'🌧️',label:'Heavy Showers',bg:'rain'},85:{icon:'🌨️',label:'Snow Showers',bg:'snow'},
  86:{icon:'🌨️',label:'Heavy Snow Showers',bg:'snow'},95:{icon:'⛈️',label:'Thunderstorm',bg:'thunderstorm'},
  96:{icon:'⛈️',label:'T-storm Hail',bg:'thunderstorm'},99:{icon:'⛈️',label:'Heavy Thunderstorm',bg:'thunderstorm'}
};
function getInfo(code,isNight){const info=WMO[code]||{icon:'🌡️',label:'Unknown',bg:'clear'};if(isNight&&info.bg==='clear')return{...info,icon:'🌙',bg:'night'};return info;}
const round=v=>Math.round(v);
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
function formatHour(iso){const h=new Date(iso).getHours();if(h===0)return'12AM';if(h===12)return'12PM';return h>12?`${h-12}PM`:`${h}AM`;}
function formatDay(iso){const d=new Date(iso+'T12:00:00');const t=new Date();t.setHours(0,0,0,0);d.setHours(0,0,0,0);if(d.getTime()===t.getTime())return'Today';return d.toLocaleDateString('en-US',{weekday:'short'});}
function fmtTime(iso){return new Date(iso).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});}
function isNight(sunrise,sunset){const now=Date.now();return now<new Date(sunrise).getTime()||now>new Date(sunset).getTime();}
function compass(deg){return['N','NE','E','SE','S','SW','W','NW'][Math.round(deg/45)%8];}
function uvLabel(uv){if(uv<=2)return'Low';if(uv<=5)return'Moderate';if(uv<=7)return'High';if(uv<=10)return'Very High';return'Extreme';}
function uid(){return Math.random().toString(36).substr(2,9);}
const state={cities:[],data:{},idx:0};
const STORE_KEY='wx_cities_v2';
const loadStored=()=>{try{return JSON.parse(localStorage.getItem(STORE_KEY))||[];}catch{return[];}};
const saveStored=cities=>{try{localStorage.setItem(STORE_KEY,JSON.stringify(cities.filter(c=>!c.isCurrentLocation)));}catch{}};
async function fetchWeather(lat,lon){const p=new URLSearchParams({latitude:lat,longitude:lon,hourly:'temperature_2m,weather_code,precipitation_probability',daily:'temperature_2m_max,temperature_2m_min,weather_code,sunrise,sunset,uv_index_max,precipitation_sum',current:'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,wind_direction_10m,precipitation,uv_index,visibility',wind_speed_unit:'kmh',timezone:'auto',forecast_days:10});const r=await fetch(`${API.weather}?${p}`);if(!r.ok)throw new Error('Weather fetch failed');return r.json();}
async function geocode(q){const p=new URLSearchParams({name:q,count:6,language:'en',format:'json'});const r=await fetch(`${API.geocode}?${p}`);if(!r.ok)throw new Error('Geocode failed');const d=await r.json();return d.results||[];}
async function reverseGeocode(lat,lon){const r=await fetch(`${API.reverse}?lat=${lat}&lon=${lon}&format=json`,{headers:{'Accept-Language':'en'}});if(!r.ok)throw new Error('Reverse geocode failed');const d=await r.json();const a=d.address||{};return{name:a.city||a.town||a.village||a.county||'My Location',country:a.country_code?a.country_code.toUpperCase():''};}
function getLocation(){return new Promise((res,rej)=>{if(!navigator.geolocation)return rej(new Error('No geolocation'));navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:10000,maximumAge:300000});});}
function processData(raw,cityInfo){const c=raw.current;const d=raw.daily;const night=isNight(d.sunrise[0],d.sunset[0]);const info=getInfo(c.weather_code,night);const current={city:cityInfo.name,country:cityInfo.country,temp:round(c.temperature_2m),feelsLike:round(c.apparent_temperature),condition:info.label,icon:info.icon,bg:info.bg,isNight:night,hi:round(d.temperature_2m_max[0]),lo:round(d.temperature_2m_min[0]),humidity:c.relative_humidity_2m,windSpeed:round(c.wind_speed_10m),windDir:c.wind_direction_10m,uv:c.uv_index||0,visibility:c.visibility||10000,precip:c.precipitation||0,sunrise:d.sunrise[0],sunset:d.sunset[0]};const now=Date.now();const hourly=[];for(let i=0;i<raw.hourly.time.length&&hourly.length<24;i++){if(new Date(raw.hourly.time[i]).getTime()<now-3600000)continue;const hNight=new Date(raw.hourly.time[i]).getHours()<6||new Date(raw.hourly.time[i]).getHours()>=20;const hInfo=getInfo(raw.hourly.weather_code[i],hNight);hourly.push({time:hourly.length===0?'Now':formatHour(raw.hourly.time[i]),icon:hInfo.icon,temp:round(raw.hourly.temperature_2m[i]),isNow:hourly.length===0});}const daily=raw.daily.time.map((t,i)=>({day:formatDay(t),icon:getInfo(raw.daily.weather_code[i]).icon,hi:round(raw.daily.temperature_2m_max[i]),lo:round(raw.daily.temperature_2m_min[i])}));return{current,hourly,daily};}
const $=id=>document.getElementById(id);
const $loading=$('loading-screen'),$app=$('app'),$bgLayer=$('bg-layer'),$pcont=$('particles-container'),$pages=$('pages-container'),$pageDots=$('page-dots-container'),$cityDots=$('city-dots'),$overlay=$('search-overlay'),$input=$('city-search-input'),$results=$('search-results'),$savedList=$('saved-cities-list'),$savedSec=$('saved-cities-section'),$clearBtn=$('clear-search'),$tmpl=$('weather-page-template');
function buildPage(city){const d=state.data[city.id];if(!d)return null;const clone=$tmpl.content.cloneNode(true);const page=clone.querySelector('.weather-page');const{current,hourly,daily}=d;page.querySelector('[data-field="city"]').textContent=current.city;page.querySelector('[data-field="temp"]').textContent=`${current.temp}°`;page.querySelector('[data-field="condition"]').textContent=current.condition;page.querySelector('[data-field="hilo"]').textContent=`H:${current.hi}°  L:${current.lo}°`;const hScroll=page.querySelector('[data-field="hourly"]');hourly.forEach(h=>{const el=document.createElement('div');el.className='hour-item'+(h.isNow?' now':'');el.innerHTML=`<span class="hour-time">${h.time}</span><span class="hour-icon">${h.icon}</span><span class="hour-temp">${h.temp}°</span>`;hScroll.appendChild(el);});const dList=page.querySelector('[data-field="daily"]');const allLo=daily.map(x=>x.lo),allHi=daily.map(x=>x.hi);const gLo=Math.min(...allLo),gRange=Math.max(...allHi)-gLo||1;daily.forEach(row=>{const el=document.createElement('div');el.className='day-row';const bLeft=((row.lo-gLo)/gRange*100).toFixed(1);const bWidth=((row.hi-row.lo)/gRange*100).toFixed(1);el.innerHTML=`<span class="day-name">${row.day}</span><span class="day-icon">${row.icon}</span><span class="day-lo">${row.lo}°</span><div class="day-bar-wrap"><div class="temp-bar-container"><div class="temp-bar-fill" style="left:${bLeft}%;width:${bWidth}%"></div></div><span class="day-hi">${row.hi}°</span></div>`;dList.appendChild(el);});const grid=page.querySelector('[data-field="info-grid"]');grid.appendChild(mkUV(current));grid.appendChild(mkWind(current));grid.appendChild(mkHumidity(current));grid.appendChild(mkVisibility(current));grid.appendChild(mkSun(current));grid.appendChild(mkPrecip(current));grid.appendChild(mkFeels(current));return page;}
function mkCard(svg,txt){const el=document.createElement('div');el.className='info-card';return[el,`<div class="info-label">${svg}${txt}</div>`];}
function mkUV(w){const[el,h]=mkCard('<svg viewBox="0 0 24 24"><path d="M12 7c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5zM2 13h2c.55 0 1-.45 1-1s-.45-1-1-1H2c-.55 0-1 .45-1 1s.45 1 1 1zm18 0h2c.55 0 1-.45 1-1s-.45-1-1-1h-2c-.55 0-1 .45-1 1s.45 1 1 1zM11 2v2c0 .55.45 1 1 1s1-.45 1-1V2c0-.55-.45-1-1-1s-1 .45-1 1zm0 18v2c0 .55.45 1 1 1s1-.45 1-1v-2c0-.55-.45-1-1-1s-1 .45-1 1z"/>'+
'</svg>','UV INDEX');const pct=clamp((w.uv/11)*100,0,100);el.innerHTML=h+`<div class="info-value">${round(w.uv)}</div><div class="uv-bar-wrap"><div class="uv-bar"><div class="uv-dot" style="left:${pct}%"></div></div></div><div class="info-sub">${uvLabel(w.uv)}</div>`;return el;}
function mkWind(w){const[el,h]=mkCard('<svg viewBox="0 0 24 24"><path d="M14.5 17c0 1.65-1.35 3-3 3s-3-1.35-3-3h2c0 .55.45 1 1 1s1-.45 1-1-.45-1-1-1H2v-2h9.5c1.65 0 3 1.35 3 3zm-3-7c0 1.65 1.35 3 3 3 1.65 0 3-1.35 3-3H15.5c0 .55-.45 1-1 1s-1-.45-1-1 .45-1 1-1H22V8h-5.5c-1.65 0-3 1.35-3 3z"/></svg>','WIND');el.innerHTML=h+`<div class="info-value">${w.windSpeed}<span class="info-unit"> km/h</span></div><div class="wind-compass"><span class="wind-arrow" style="transform:rotate(${w.windDir}deg)">↑</span></div><div class="info-sub">${compass(w.windDir)}</div>`;return el;}
function mkHumidity(w){const[el,h]=mkCard('<svg viewBox="0 0 24 24"><path d="M12 2c-5.33 4.55-8 8.48-8 11.8 0 4.98 3.8 8.2 8 8.2s8-3.22 8-8.2c0-3.32-2.67-7.25-8-11.8z"/></svg>','HUMIDITY');const label=w.humidity<30?'Very Dry':w.humidity<50?'Comfortable':w.humidity<70?'Humid':'Very Humid';el.innerHTML=h+`<div class="info-value">${w.humidity}<span class="info-unit">%</span></div><div class="precip-bar"><div class="precip-fill" style="width:${w.humidity}%"></div></div><div class="info-sub">${label}</div>`;return el;}
function mkVisibility(w){const[el,h]=mkCard('<svg viewBox="0 0 24 24"><path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"/></svg>','VISIBILITY');const km=round(w.visibility/1000);const level=clamp(Math.floor(km/2),0,4);let bars='';for(let i=0;i<5;i++)bars+=`<div class="vis-bar ${i<=level?'active':''}" style="height:${8+i*6}px"></div>`;const label=km>=10?'Clear':km>=5?'Good':km>=2?'Moderate':'Poor';el.innerHTML=h+`<div class="info-value">${km}<span class="info-unit"> km</span></div><div class="visibility-bars">${bars}</div><div class="info-sub">${label}</div>`;return el;}
function mkSun(w){const[el,h]=mkCard('<svg viewBox="0 0 24 24"><path d="M12 7c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5z"/></svg>','SUNRISE & SUNSET');el.className+=' sunrise-card';const now=Date.now();const rT=new Date(w.sunrise).getTime(),sT=new Date(w.sunset).getTime();const pct=clamp((now-rT)/(sT-rT),0,1);const angle=pct*Math.PI;const cx=50,cy=48,r=36;const sunX=(cx-r*Math.cos(angle)).toFixed(1);const sunY=(cy-r*Math.sin(angle)).toFixed(1);el.innerHTML=h+`<div class="sun-arc"><svg viewBox="0 0 100 60" fill="none"><path d="M ${cx-r} ${cy} A ${r} ${r} 0 0 1 ${cx+r} ${cy}" stroke="rgba(255,255,255,0.2)" stroke-width="2" fill="none" stroke-dasharray="4 3"/><circle cx="${sunX}" cy="${sunY}" r="5" fill="#ffd54f"/></svg></div><div class="sun-times"><div class="sun-time-item"><div class="info-sub">Sunrise</div><div style="font-size:15px;color:white;font-weight:500">${fmtTime(w.sunrise)}</div></div><div class="sun-time-item"><div class="info-sub">Sunset</div><div style="font-size:15px;color:white;font-weight:500">${fmtTime(w.sunset)}</div></div></div>`;return el;}
function mkPrecip(w){const[el,h]=mkCard('<svg viewBox="0 0 24 24"><path d="M12 2c-5.33 4.55-8 8.48-8 11.8 0 4.98 3.8 8.2 8 8.2s8-3.22 8-8.2c0-3.32-2.67-7.25-8-11.8z"/></svg>','PRECIPITATION');el.innerHTML=h+`<div class="info-value">${w.precip}<span class="info-unit"> mm</span></div><div class="precip-bar"><div class="precip-fill" style="width:${clamp(w.precip*10,0,100)}%"></div></div><div class="info-sub">In the last hour</div>`;return el;}
function mkFeels(w){const[el,h]=mkCard('<svg viewBox="0 0 24 24"><path d="M15 13V5c0-1.66-1.34-3-3-3S9 3.34 9 5v8c-1.21.91-2 2.37-2 4 0 2.76 2.24 5 5 5s5-2.24 5-5c0-1.63-.79-3.09-2-4zm-4-8c0-.55.45-1 1-1s1 .45 1 1h-1v1h1v2h-1v1h1v1h-2V5z"/></svg>','FEELS LIKE');const diff=w.feelsLike-w.temp;const why=diff<-3?'Wind makes it colder':diff>3?'Humidity adds warmth':'Similar to actual temp';el.innerHTML=h+`<div class="info-value">${w.feelsLike}°</div><div class="info-sub">${why}</div>`;return el;}
const ALL_BG=['bg-clear-day','bg-clear-night','bg-cloudy','bg-rain','bg-snow','bg-thunderstorm','bg-fog','bg-sunrise','bg-sunset'];
function applyBg(current){ALL_BG.forEach(c=>$bgLayer.classList.remove(c));const h=new Date().getHours();let cls;if(current.isNight||current.bg==='night')cls='bg-clear-night';else if(current.bg==='clear'){if(h>=5&&h<=7)cls='bg-sunrise';else if(h>=18&&h<=20)cls='bg-sunset';else cls='bg-clear-day';}else cls='bg-'+current.bg;$bgLayer.classList.add(cls||'bg-clear-day');spawnParticles(cls);}
function spawnParticles(bg){$pcont.innerHTML='';if(bg==='bg-clear-night'){for(let i=0;i<80;i++){const s=document.createElement('div');s.className='star';const sz=Math.random()*2.5+0.8;s.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*70}%;width:${sz}px;height:${sz}px;--dur:${(Math.random()*3+2).toFixed(1)}s;--delay:-${(Math.random()*5).toFixed(1)}s`;$pcont.appendChild(s);}}else if(bg==='bg-rain'||bg==='bg-thunderstorm'){for(let i=0;i<60;i++){const r=document.createElement('div');r.className='rain-drop';const ht=Math.random()*20+15;r.style.cssText=`left:${Math.random()*105}%;top:${-ht}px;height:${ht}px;--dur:${(Math.random()*0.5+0.6).toFixed(2)}s;--delay:-${(Math.random()*2).toFixed(2)}s`;$pcont.appendChild(r);}}else if(bg==='bg-snow'){for(let i=0;i<40;i++){const f=document.createElement('div');f.className='snow-flake';const sz=Math.random()*5+3;f.style.cssText=`left:${Math.random()*100}%;top:-${sz}px;width:${sz}px;height:${sz}px;--dur:${(Math.random()*3+3).toFixed(1)}s;--delay:-${(Math.random()*6).toFixed(1)}s;--drift:${(Math.random()*60-30).toFixed(0)}px`;$pcont.appendChild(f);}}}
function renderAll(){$pages.innerHTML='';$pageDots.innerHTML='';$cityDots.innerHTML='';state.cities.forEach((city,i)=>{const page=buildPage(city);if(!page)return;page.style.transform=`translateX(${(i-state.idx)*100}%)`;$pages.appendChild(page);const pd=document.createElement('div');pd.className='page-dot'+(i===state.idx?' active':'');$pageDots.appendChild(pd);const cd=document.createElement('div');cd.className='city-dot'+(i===state.idx?' active':'');cd.addEventListener('click',()=>goTo(i));$cityDots.appendChild(cd);});const cur=state.data[state.cities[state.idx]?.id]?.current;if(cur)applyBg(cur);}
function goTo(idx){if(idx<0||idx>=state.cities.length)return;state.idx=idx;$pages.querySelectorAll('.weather-page').forEach((p,i)=>{p.style.transition='transform 0.4s cubic-bezier(0.4,0,0.2,1)';p.style.transform=`translateX(${(i-idx)*100}%)`;});$pageDots.querySelectorAll('.page-dot').forEach((d,i)=>d.classList.toggle('active',i===idx));$cityDots.querySelectorAll('.city-dot').forEach((d,i)=>d.classList.toggle('active',i===idx));const cur=state.data[state.cities[idx]?.id]?.current;if(cur)applyBg(cur);}
let swipeX=0,swipeY=0,swiping=false,swipeMoved=false;
$pages.addEventListener('touchstart',e=>{swipeX=e.touches[0].clientX;swipeY=e.touches[0].clientY;swiping=true;swipeMoved=false;},{passive:true});
$pages.addEventListener('touchmove',e=>{if(!swiping)return;if(Math.abs(e.touches[0].clientX-swipeX)>Math.abs(e.touches[0].clientY-swipeY))swipeMoved=true;},{passive:true});
$pages.addEventListener('touchend',e=>{if(!swiping||!swipeMoved){swiping=false;return;}const dx=e.changedTouches[0].clientX-swipeX;swiping=false;if(dx<-50)goTo(state.idx+1);else if(dx>50)goTo(state.idx-1);});
let searchTimer=null;
function openSearch(){$overlay.classList.remove('hidden');requestAnimationFrame(()=>$overlay.classList.add('visible'));setTimeout(()=>$input.focus(),80);renderSaved();}
function closeSearch(){$overlay.classList.remove('visible');setTimeout(()=>{$overlay.classList.add('hidden');$input.value='';$results.innerHTML='';$clearBtn.classList.add('hidden');$savedSec.style.display='';},300);}
$('open-search-btn').addEventListener('click',openSearch);
$('search-cancel').addEventListener('click',closeSearch);
$('location-btn').addEventListener('click',()=>loadCurrentLocation());
$input.addEventListener('input',()=>{const q=$input.value.trim();$clearBtn.classList.toggle('hidden',!q);$savedSec.style.display=q?'none':'';clearTimeout(searchTimer);if(!q){$results.innerHTML='';return;}searchTimer=setTimeout(()=>doSearch(q),400);});
$clearBtn.addEventListener('click',()=>{$input.value='';$results.innerHTML='';$clearBtn.classList.add('hidden');$savedSec.style.display='';$input.focus();});
async function doSearch(q){$results.innerHTML='<div class="no-results">Searching…</div>';try{const list=await geocode(q);if(!list.length){$results.innerHTML=`<div class="no-results">No results for "${q}"</div>`;return;}$results.innerHTML='';list.forEach(r=>{const el=document.createElement('div');el.className='search-result-item';el.innerHTML=`<div class="result-icon"><svg viewBox="0 0 24 24"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7z"/></svg></div><div><div class="result-name">${r.name}${r.admin1?', '+r.admin1:''}</div><div class="result-country">${r.country||''}</div></div>`;el.addEventListener('click',()=>selectCity(r));$results.appendChild(el);});}catch{$results.innerHTML='<div class="no-results">Search failed.</div>';}}
async function selectCity(r){closeSearch();const cityId=uid();const cityInfo={id:cityId,name:r.name,country:r.country_code?.toUpperCase()||r.country||'',lat:r.latitude,lon:r.longitude,isCurrentLocation:false};const dup=state.cities.find(c=>Math.abs(c.lat-cityInfo.lat)<0.05&&Math.abs(c.lon-cityInfo.lon)<0.05);if(dup){goTo(state.cities.indexOf(dup));return;}showRefresh('Loading…');try{const raw=await fetchWeather(cityInfo.lat,cityInfo.lon);const d=processData(raw,cityInfo);state.cities.push(cityInfo);state.data[cityId]=d;saveStored(state.cities);renderAll();goTo(state.cities.length-1);}catch{alert('Failed to load weather.');}finally{hideRefresh();}}
function getCardBg(bg,night){const m={clear:'linear-gradient(135deg,rgba(41,98,255,.5),rgba(0,176,255,.3))',night:'linear-gradient(135deg,rgba(10,14,30,.6),rgba(30,40,80,.4))',cloudy:'linear-gradient(135deg,rgba(84,110,122,.5),rgba(96,125,139,.3))',rain:'linear-gradient(135deg,rgba(26,42,62,.6),rgba(38,50,68,.4))',snow:'linear-gradient(135deg,rgba(176,190,197,.5),rgba(144,164,174,.3))',thunderstorm:'linear-gradient(135deg,rgba(26,26,46,.6),rgba(22,33,62,.4))',fog:'linear-gradient(135deg,rgba(158,158,158,.5),rgba(117,117,117,.3))'};return m[night?'night':bg]||m.clear;}
function renderSaved(){$savedList.innerHTML='';if(!state.cities.length){$savedList.innerHTML='<div class="saved-empty">No saved cities yet.<br>Search to add a city.</div>';return;}state.cities.forEach((city,i)=>{const d=state.data[city.id];if(!d)return;const c=d.current;const card=document.createElement('div');card.className='saved-city-card';card.style.background=getCardBg(c.bg,c.isNight);card.innerHTML=`<div class="saved-city-info"><div class="saved-city-name">${city.name}</div>${city.isCurrentLocation?`<div class="location-badge"><svg viewBox="0 0 24 24"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7z"/></svg>My Location</div>`:`<div class="saved-city-time">${c.condition}</div>`}</div><div class="saved-city-right"><div class="saved-city-temp">${c.temp}°</div><div class="saved-city-cond">H:${c.hi}° L:${c.lo}°</div></div>${!city.isCurrentLocation?`<button class="saved-city-delete"><svg viewBox="0 0 24 24"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg></button>`:''}`;card.addEventListener('click',e=>{if(e.target.closest('.saved-city-delete'))return;closeSearch();goTo(i);});let pt;card.addEventListener('touchstart',()=>{pt=setTimeout(()=>card.classList.toggle('show-delete'),600);},{passive:true});card.addEventListener('touchend',()=>clearTimeout(pt),{passive:true});const del=card.querySelector('.saved-city-delete');if(del)del.addEventListener('click',e=>{e.stopPropagation();removeCity(city.id);renderSaved();});$savedList.appendChild(card);});}
function removeCity(id){const i=state.cities.findIndex(c=>c.id===id);if(i===-1)return;state.cities.splice(i,1);delete state.data[id];saveStored(state.cities);if(state.idx>=state.cities.length)state.idx=Math.max(0,state.cities.length-1);renderAll();}
let $rfBar=null;
function showRefresh(msg='Updating…'){if(!$rfBar){$rfBar=document.createElement('div');$rfBar.className='refresh-indicator';$rfBar.innerHTML='<div class="refresh-spin"></div><span></span>';document.body.appendChild($rfBar);}$rfBar.querySelector('span').textContent=msg;requestAnimationFrame(()=>$rfBar.classList.add('show'));}
function hideRefresh(){$rfBar&&$rfBar.classList.remove('show');}
async function loadCurrentLocation(){showRefresh('Getting location…');try{const pos=await getLocation();const{latitude:lat,longitude:lon}=pos.coords;showRefresh('Fetching weather…');const[geo,raw]=await Promise.all([reverseGeocode(lat,lon),fetchWeather(lat,lon)]);const oldIdx=state.cities.findIndex(c=>c.isCurrentLocation);if(oldIdx!==-1){delete state.data[state.cities[oldIdx].id];state.cities.splice(oldIdx,1);}const id='current';const info={id,name:geo.name,country:geo.country,lat,lon,isCurrentLocation:true};state.cities.unshift(info);state.data[id]=processData(raw,info);renderAll();goTo(0);}catch(e){console.warn('Location error:',e.message);if(!state.cities.length){showError('Location Denied','Allow location or search for a city.');showApp();openSearch();}}finally{hideRefresh();}}
async function init(){const stored=loadStored();const[locResult,...savedResults]=await Promise.allSettled([Promise.race([(async()=>{const pos=await getLocation();const{latitude:lat,longitude:lon}=pos.coords;const[geo,raw]=await Promise.all([reverseGeocode(lat,lon),fetchWeather(lat,lon)]);return{id:'current',name:geo.name,country:geo.country,lat,lon,isCurrentLocation:true,raw};})(),new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),8000))]),...stored.map(async city=>{const raw=await fetchWeather(city.lat,city.lon);return{...city,raw};})]);if(locResult.status==='fulfilled'){const r=locResult.value;state.cities.push({id:r.id,name:r.name,country:r.country,lat:r.lat,lon:r.lon,isCurrentLocation:true});state.data[r.id]=processData(r.raw,r);}savedResults.forEach(res=>{if(res.status!=='fulfilled')return;const r=res.value;if(state.cities.find(c=>c.id===r.id))return;state.cities.push({id:r.id,name:r.name,country:r.country,lat:r.lat,lon:r.lon,isCurrentLocation:false});state.data[r.id]=processData(r.raw,r);});hideLoading();if(!state.cities.length){showApp();showError('No Data','Search for a city to get started.');openSearch();return;}showApp();renderAll();goTo(0);}
function hideLoading(){$loading.classList.add('fade-out');setTimeout(()=>$loading.style.display='none',600);}
function showApp(){$app.classList.remove('hidden');requestAnimationFrame(()=>$app.classList.add('visible'));}
function showError(title,msg){$pages.innerHTML=`<div class="weather-page"><div class="page-scroll"><div class="error-screen"><div class="error-icon">⛅</div><div class="error-title">${title}</div><div class="error-msg">${msg}</div><button class="retry-btn" onclick="location.reload()">Try Again</button></div></div></div>`;}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSearch();if(e.key==='Enter'&&document.activeElement===$input)doSearch($input.value.trim());});
init();
